CREATE TABLE "AR_RICHTLINIE" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"RICHTLINIE_ID"	TEXT NOT NULL UNIQUE,
	"DETAIL_ID_AKTUELL"	INTEGER,
	"QUELLE"	TEXT NOT NULL CHECK("QUELLE" IN ('ARCH', 'TECH')),
	"LEBENSZYKLUS"	TEXT NOT NULL CHECK("LEBENSZYKLUS" IN ('AKTIV', 'ERSETZT', 'ENTFERNT')),
	"NACHFOLGER_ID"	TEXT,
	"ERSTELLT"	DATETIME NOT NULL DEFAULT current_timestamp,
	"AKTUALISIERT"	DATETIME NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TRIGGER [tr_richtlinie_aktualisiert]
    AFTER UPDATE
    ON AR_RICHTLINIE
	FOR EACH ROW
	WHEN NEW.AKTUALISIERT <= OLD.AKTUALISIERT
BEGIN
    UPDATE AR_RICHTLINIE SET AKTUALISIERT=CURRENT_TIMESTAMP where ID=OLD.ID;
END;


CREATE TABLE "AR_DETAIL" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"RICHTLINIE_ID"	INTEGER NOT NULL,
	"VERSION"	TEXT NOT NULL,
	"JAHR"	INTEGER NOT NULL,
	"THEMENBEREICH"	TEXT,
	"BEZEICHNUNG"	TEXT NOT NULL,
	"VERBINDLICHKEIT"	TEXT NOT NULL CHECK("VERBINDLICHKEIT" IN ('MUSS', 'SOLL', 'KANN', 'DARF NICHT')),
	"BESCHREIBUNG"	TEXT NOT NULL,
	"ERSTELLT"	DATETIME NOT NULL DEFAULT current_timestamp,
	"AKTUALISIERT"	DATETIME NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE UNIQUE INDEX "idx_detail_richtlinie_id_version" ON "AR_DETAIL" (
	"RICHTLINIE_ID",
	"VERSION"
);

CREATE INDEX "idx_detail_version" ON "AR_DETAIL" (
	"VERSION"
);

CREATE TRIGGER [tr_detail_aktualisiert]
    AFTER UPDATE
    ON AR_DETAIL
	FOR EACH ROW
	WHEN NEW.AKTUALISIERT <= OLD.AKTUALISIERT
BEGIN
    UPDATE AR_DETAIL SET AKTUALISIERT=CURRENT_TIMESTAMP where ID=OLD.ID;
END;


CREATE TABLE "AR_TAG" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"RICHTLINIE_ID"	TEXT NOT NULL,
	"TAG"	TEXT NOT NULL,
	"ERSTELLT"	DATETIME NOT NULL DEFAULT current_timestamp,
	"AKTUALISIERT"	DATETIME NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TRIGGER [tr_tag_aktualisiert]
    AFTER UPDATE
    ON AR_TAG
	FOR EACH ROW
	WHEN NEW.AKTUALISIERT <= OLD.AKTUALISIERT
BEGIN
    UPDATE AR_TAG SET AKTUALISIERT=CURRENT_TIMESTAMP where ID=OLD.ID;
END;


CREATE TABLE "AR_NOTIZ" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"RICHTLINIE_ID"	INTEGER NOT NULL,
	"TYP"	TEXT NOT NULL DEFAULT 'NOTIZ',
	"PRIO"	TEXT NOT NULL DEFAULT 'MITTEL' CHECK("PRIO" IN ('SEHR GERING', 'GERING', 'MITTEL', 'HOCH', 'SEHR HOCH')),
	"BESCHREIBUNG"	TEXT NOT NULL,
	"ERSTELLT"	DATETIME NOT NULL DEFAULT current_timestamp,
	"AKTUALISIERT"	DATETIME NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TRIGGER [tr_notiz_aktualisiert]
    AFTER UPDATE
    ON "AR_NOTIZ"
	FOR EACH ROW
	WHEN NEW.AKTUALISIERT <= OLD.AKTUALISIERT
BEGIN
    UPDATE "AR_NOTIZ" SET AKTUALISIERT=CURRENT_TIMESTAMP where ID=OLD.ID;
END;


CREATE VIEW "Aktuelle Architekturrichtlinien ohne Tags oder Relevanzbewertung" AS
select
    r.richtlinie_id ID,
    r.QUELLE Quelle,
	d.version Version,
    d.BEZEICHNUNG Bezeichnung,
	(select count(id) from AR_TAG t1 where t1.RICHTLINIE_ID=r.RICHTLINIE_ID) "Anz Tags",
	(select count(id) from AR_NOTIZ rel1 where rel1.RICHTLINIE_ID=r.RICHTLINIE_ID and rel1.TYP='RELEVANZ SYSARCH') "Anz Relevanz"
from
    AR_RICHTLINIE r
    inner join AR_DETAIL d on d.id=r.DETAIL_ID_AKTUELL
where 1=1
    and (
	  (select count(id) from AR_TAG t1 where t1.RICHTLINIE_ID=r.RICHTLINIE_ID) = 0
	  or
	  (select count(id) from AR_NOTIZ rel1 where rel1.RICHTLINIE_ID=r.RICHTLINIE_ID and rel1.TYP='RELEVANZ SYSARCH') = 0
	  )
order by
    r.Quelle asc,
    r.RICHTLINIE_ID asc
;


CREATE VIEW "Tagfilter Aktuell" AS select
  t.TAG Tag,
  r.richtlinie_id ID,
  d.BEZEICHNUNG Bezeichnung,
  d.VERBINDLICHKEIT Verbindlichkeit,
  r.QUELLE Quelle,
  d.version Version,
  d.jahr Jahr
from
  AR_RICHTLINIE r
  inner join AR_DETAIL d on d.id=r.DETAIL_ID_AKTUELL
  join AR_TAG t on t.RICHTLINIE_ID=d.RICHTLINIE_ID
where 1=1
;